services:
  postgres-writer:
    container_name: postgres-writer
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: may-the-force-be-with-you
    ports:
      - "5432:5432"
    volumes:
      - backend:/var/lib/postgresql/data
    networks:
      - backend

  postgres-reader:
    container_name: postgres-reader
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: may-the-force-be-with-you
    ports:
      - "5433:5432"
    volumes:
      - backend:/var/lib/postgresql/data:ro
    depends_on:
      - postgres-writer
    networks:
      - backend

networks:
  backend:

volumes:
  backend:
    name: kotlin_backends_postgres_data
    external: true
